apiVersion: v1
kind: PersistentVolume
metadata:
  name: hyeonseong-nfs-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
  nfs:
    path: /var/nfs/general/
    server: 129.254.202.111