apiVersion: v1
kind: Service
metadata:
  name: hyeonseongreqsvc
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30111
  selector:
    app: hyeonseong-req                    
